'use strict';var _typeof='function'==typeof Symbol&&'symbol'==typeof Symbol.iterator?function(a){return typeof a}:function(a){return a&&'function'==typeof Symbol&&a.constructor===Symbol&&a!==Symbol.prototype?'symbol':typeof a},_extends=Object.assign||function(a){for(var b,c=1;c<arguments.length;c++)for(var d in b=arguments[c],b)Object.prototype.hasOwnProperty.call(b,d)&&(a[d]=b[d]);return a},_createClass=function(){function a(a,b){for(var c,d=0;d<b.length;d++)c=b[d],c.enumerable=c.enumerable||!1,c.configurable=!0,'value'in c&&(c.writable=!0),Object.defineProperty(a,c.key,c)}return function(b,c,d){return c&&a(b.prototype,c),d&&a(b,d),b}}(),_templateObject=_taggedTemplateLiteral([''],['']);function _taggedTemplateLiteral(a,b){return Object.freeze(Object.defineProperties(a,{raw:{value:Object.freeze(b)}}))}function _classCallCheck(a,b){if(!(a instanceof b))throw new TypeError('Cannot call a class as a function')}var DateGroupForm=function(){function a(){var b=0<arguments.length&&void 0!==arguments[0]?arguments[0]:[],c=1<arguments.length&&void 0!==arguments[1]?arguments[1]:{};_classCallCheck(this,a),this.LargeNameMonth=['January','February','March','April','May','June','July','August','September','October','November','December'],this.ShortNameMonth=this.LargeNameMonth.map(function(a){return a.slice(0,3)});// Constructor Default Option
var d={// Month
monthFormat:'large',monthSelectName:'Select Month',// Year
minYear:new Date().getFullYear()-90,maxYear:new Date().getFullYear(),// Default Update
defaultDay:0,defaultMonth:0,defaultYear:0,// onChange Option
onChangeClear:!0,onChangeGet:!1,// ClassName
toggleErrorClass:!0,toggleErrorClassName:'error',optionClassName:''};this.opt=_extends({},d,c),this.opt.minYear=+this.opt.minYear,this.opt.maxYear=+this.opt.maxYear,this.dateGroupObj={day:null,month:null,year:null,error:null},this.day=0,this.month=0,this.year=0,this.isArrayFirstParams(b),this.isObjectSecondParams(c),0==+this.opt.defaultDay||isNaN(+this.opt.defaultDay)||(this.day=+this.opt.defaultDay,this.dateGroupObj.day.value=this.day),0==+this.opt.defaultMonth||isNaN(+this.opt.defaultMonth)||(this.month=+this.opt.defaultMonth,this.dateGroupObj.month.value=this.month),0==+this.opt.defaultYear||isNaN(+this.opt.defaultYear)||(this.year=+this.opt.defaultYear,this.dateGroupObj.year.value=this.year),this.getDate=this.year+'-'+this.setTwoDigitMonth(this.month)+('-'+this.day)}// Set -----------
// User Can Set this.setDay('#day').setMonth('#month').setYear('#year')
return _createClass(a,[{key:'setDay',value:function b(a){return this.setDayElement(this.returnCheckElement(a))}},{key:'setMonth',value:function b(a){return this.setMonthElement(this.returnCheckElement(a))}},{key:'setYear',value:function b(a){return this.setYearElement(this.returnCheckElement(a))}},{key:'setError',value:function b(a){return this.setErrorElement(this.returnCheckElement(a))}// Option Set ----------
// User Can Add Option
},{key:'option',value:function b(){var a=0<arguments.length&&void 0!==arguments[0]?arguments[0]:{};return this.opt=_extends({},this.opt,a),a.monthSelectName&&this.setSelectorMonthList(),this}// Set Element ----------
},{key:'setDayElement',value:function c(a){var b=this;return a.maxLength=2,a.addEventListener('change',function(a){return b.dayElementOnChange(a)}),a.addEventListener('keyup',function(a){return b.dayElementOnChange(a)}),this.dateGroupObj.day=a,this}},{key:'setMonthElement',value:function c(a){var b=this;return this.dateGroupObj.month=a,a.addEventListener('change',function(a){return b.monthElementOnChange(a)}),a.addEventListener('keyup',function(a){return b.monthElementOnChange(a)}),this.setSelectorMonthList(),this}},{key:'setYearElement',value:function c(a){var b=this;return a.maxLength=4,a.addEventListener('change',function(a){return b.yearElementOnChange(a)}),a.addEventListener('keyup',function(a){return b.yearElementOnChange(a)}),this.dateGroupObj.year=a,this}},{key:'setErrorElement',value:function b(a){return this.dateGroupObj.error=a,this}// getDateGp ----------
},{key:'getDateGroup',value:function a(){return this.dateGroupObj}},{key:'getDay',value:function a(){return this.day}},{key:'getMonth',value:function a(){return this.month}},{key:'getMonthByName',value:function b(){var a=+this.month;// console.log('month', month)
return 0==a?this.opt.monthSelectName:0<a&&13>a?'large'===this.opt.monthFormat?this.LargeNameMonth[a-1]:this.ShortNameMonth[a-1]:'Error'}},{key:'getYear',value:function a(){return this.year}// Change Event ----------
},{key:'dayElementOnChange',value:function c(a){var b=a.target.value;this.day=+b,this.onChangeClearDate(),this.allOnChange()}},{key:'monthElementOnChange',value:function c(a){var b=a.target.value;this.month=+b,this.onChangeClearDate(),this.allOnChange()}},{key:'yearElementOnChange',value:function c(a){var b=a.target.value;this.year=+b,this.onChangeClearDate(),this.allOnChange()}},{key:'allOnChange',value:function a(){this.getDate=this.year+'-'+this.setTwoDigitMonth(this.month)+('-'+this.day),null!==this.opt.onChangeGet&&'function'==typeof this.opt.onChangeGet&&this.opt.onChangeGet({day:+this.day,month:+this.month,year:+this.year,getBy:function b(a){return''+this.day+a+this.month+a+this.year}})}// Return Element For Given #div or .div , ID or ClassName
},{key:'returnCheckElement',value:function c(a){var b=1<arguments.length&&void 0!==arguments[1]?arguments[1]:'';if('string'==typeof a){// Check # or . is the Selector
if('#'!==a[0]&&'.'!==a[0])throw new Error(a+' Not Selector');var d='#'===a[0]?document.getElementById(a.split('').filter(function(a){return'#'!==a}).join(_templateObject)):document.querySelector(a);if(null===d)throw Error('Your Index '+b+' => '+a+' is Not Element \nLwin ');return d}if('object'===('undefined'==typeof a?'undefined':_typeof(a))&&null!==a){var e=Object.keys(a).length;if(0===e)throw Error('Your Index '+b+' => '+a+' is Not Element \nLwin ');return a[0]}throw Error('Your Index '+b+' => '+a+' is Not Element \nLwin ')}// Set Selector Month
},{key:'setSelectorMonthList',value:function c(){var a=this,b='large'===this.opt.monthFormat?[this.opt.monthSelectName].concat(this.LargeNameMonth):[this.opt.monthSelectName].concat(this.ShortNameMonth);// console.log('Call SetSelector Month List ', this.dateGroupObj['month'])
null!==this.dateGroupObj.month&&(this.dateGroupObj.month.innerHTML=b.map(function(b,c){return'<option class="'+a.opt.optionClassName+'" value='+c+'>'+b+'</option>'}).join(_templateObject))}// Validation ----------
},{key:'validateDay',value:function b(){var a=this.day;return!(isNaN(a)||''==a)&&!!(0<a&&32>a)}},{key:'validateMonth',value:function b(){var a=this.month;return!(isNaN(a)||''==a)&&!!(0<a&&13>a)}},{key:'validateYear',value:function b(){var a=this.year;return!(isNaN(a)||''==a)&&!!(a>=this.opt.minYear&&a<=this.opt.maxYear)}},{key:'allValid',value:function a(){return this.validateDay()&&this.validateMonth()&&this.validateYear()}},{key:'isValid',value:function(){var a=!1;if(this.allValid()){if(2==this.month){var b=28;return 0==this.year%4&&(b=29),this.day<=b}if(-1!==[4,6,9,11].indexOf(+this.month))// console.log('this.month', this.month)
return 31>+this.day;a=this.allValid()}return a}},{key:'showError',value:function e(){// console.log('Show Error')
if(null!==this.dateGroupObj.error&&!this.isValid()){var a='Please Check February and Date';-1!==[4,6,9,11].indexOf(+this.month)&&30<+this.day&&(a=' Can\'t 31 in this Month '),this.validateDay()?this.validateMonth()?!this.validateYear()&&(a='Please Enter Valid Year'):a='Please Enter Valid Month':a='Please Enter Valid Day',this.dateGroupObj.error.innerHTML=a}if(this.opt.toggleErrorClass){var b=this.dateGroupObj.day,c=this.dateGroupObj.month,d=this.dateGroupObj.year;null!==b&&b?b.classList.add(this.opt.toggleErrorClassName):'',null!==c&&c?c.classList.add(this.opt.toggleErrorClassName):'',null!==d&&d?d.classList.add(this.opt.toggleErrorClassName):''}}},{key:'clearError',value:function e(){if(null!==this.dateGroupObj.error&&this.validateDay()&&this.validateMonth()&&this.validateYear()&&(this.dateGroupObj.error.innerHTML='',this.opt.toggleErrorClass)){var a=this.dateGroupObj.day,b=this.dateGroupObj.month,c=this.dateGroupObj.year,d=this.opt.toggleErrorClassName;a.classList.remove(d),b.classList.remove(d),c.classList.remove(d)}}},{key:'onChangeClearDate',value:function a(){this.opt.onChangeClear&&null!==this.dateGroupObj.error&&this.clearError()}// 2dight Set Month
},{key:'setTwoDigitMonth',value:function b(a){return 10>a?'0'+a.toString():a.toString()}// First Params Is Elements CheckOut
},{key:'isArrayFirstParams',value:function c(a){var b=this;a.forEach(function(a,c){var d=b.returnCheckElement(a,c);0===c&&b.setDayElement(d),1===c&&b.setMonthElement(d),2===c&&b.setYearElement(d),3===c&&b.setErrorElement(d)})}//Object
},{key:'isObjectSecondParams',value:function b(a){if('object'!==('undefined'==typeof a?'undefined':_typeof(a))&&'function'!=typeof a||null===a)throw new Error('Second Param Not Object')}}]),a}();